# Generated by Django 5.2.4 on 2025-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('pages', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=30)),
                ('publication_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipping_cost', models.CharField(choices=[('Free Shipping', 'Free Shipping'), ('Standard Shipping', 'Standard Shipping'), ('Express Shipping', 'Express Shipping'), ('International Shipping', 'International Shipping'), ('In-Store Pickup', 'In-Store Pickup'), ('outof stock', 'Out of Stock'), ('preorder', 'Preorder')], default='Free Shipping', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='book_images/')),
            ],
        ),
    ]
