# Generated by Django 5.2.4 on 2025-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='book',
            name='hardcover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='paperback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='shipping_cost',
            field=models.CharField(choices=[('Free Shipping', 'Free Shipping'), ('Standard Shipping', 'Standard Shipping'), ('Express Shipping', 'Express Shipping'), ('International Shipping', 'International Shipping'), ('Out of stock', 'Out of Stock'), ('Preorder', 'Preorder')], default='Free Shipping', max_length=100),
        ),
    ]
