# Generated by Django 5.2.4 on 2025-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
