# Generated by Django 5.2.4 on 2025-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='hardcover',
            field=models.CharField(default='Unavailable', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='paperback',
            field=models.CharField(default='Unavailable', max_length=100),
        ),
    ]
